#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export PATH=$PATH:/usr/local/go/bin
cd $SCRIPT_DIR/../../backend
$(go env GOPATH)/bin/golangci-lint run ./*.go